"""
This script checks if all files in the current directory and its subdirectories
contain the appropriate license information.

There are the following license types that are used in the project:
    - ENCL: This license is used for all files containing Evmos IP.
    - LGPL3: This license is used for all files that are generated by the Cosmos SDK.
    - Geth: This license is used for all files that are copied from the Geth repository.
"""
import os
import re
import sys
from typing import Dict, List

# Check all Go or Protobuf files, that are neither generated nor test files.
FILTER: re.Pattern = re.compile(
    r"^((?!(_test|\.pb|\.pb\.gw)\.go$).)*\.(go|proto)$")

# List of files with a LGPL3 license.
EXEMPT_FILES: List[str] = [
    r"x/revenue/v1/",  # All files in this folder
    r"x/claims/genesis\.go$",
    r"x/erc20/keeper/proposals\.go$",
    r"x/erc20/types/utils\.go$",
    r"proto/evmos/revenue/v1/",  # All files in this folder
    r"proto/evmos/claims/v1/genesis\.proto$",
]

# List of folders that should be ignored.
IGNORED_FOLDERS: List[str] = [
    r"tests/solidity/node_modules",
]

LGPL3_LICENSE = [
    "// Copyright PaxLabs Ltd.(Paxeer Network)\n",
    "// Paxeer Network Non-Commercial License 1.0 (ENCL-1.0)\n"
]

ENCL_LICENSE = [
     "// Copyright PaxLabs Ltd.(Paxeer Network)\n",
    "// Paxeer Network Non-Commercial License 1.0 (ENCL-1.0)(https://github.com/Paxeer-Network/hyperpaxeer-os/blob/main/LICENSE_FAQ.md)\n"
]


def check_licenses_in_path(
    path: str,
    name_filter: re.Pattern = re.compile(".*"),
    fix: bool = False,
) -> Dict[str, int]:
    """
    Iterate over all files in the current directory and its subdirectories
    and check if the appropriate licenses are contained in the files.
    If fix=True, also fix files with missing or incorrect licenses.
    """

    files_with_wrong_license = []
    n_files = 0
    n_files_with = 0
    n_files_generated = 0
    n_files_lic_removed = 0
    n_files_geth = 0
    n_files_lgpl3 = 0
    n_files_encl = 0
    n_files_fixed = 0

    for root, _, files in os.walk(path):
        if any([re.search(folder, root) for folder in IGNORED_FOLDERS]):
            continue
        for file in files:
            full_path = os.path.join(root, file)
            if not name_filter.search(full_path):
                continue

            n_files += 1

            lgpl3 = check_if_in_exempt_files(full_path)
            checked_license = LGPL3_LICENSE if lgpl3 else ENCL_LICENSE

            found = check_license_in_file(
                os.path.join(root, file), checked_license)
            if found is True:
                n_files_with += 1
                if lgpl3:
                    n_files_lgpl3 += 1
                else:
                    n_files_encl += 1
            elif found == "generated":
                n_files_with += 1
                n_files_generated += 1
                continue
            elif found == "geth":
                n_files_with += 1
                n_files_geth += 1
                continue
            else:
                files_with_wrong_license.append(full_path)
                if fix:
                    fix_license_in_file(full_path, checked_license)
                    n_files_fixed += 1
                    n_files_with += 1
                    if lgpl3:
                        n_files_lgpl3 += 1
                    else:
                        n_files_encl += 1

    print(f"\n{n_files_with}/{n_files} contain a license comment")
    print(f" -> {n_files_generated} are generated files")
    print(f" -> {n_files_geth} have a geth license")
    print(f" -> {n_files_lgpl3} have the LGPL3 license")
    print(f" -> {n_files_encl} have the ENCL license")
    if fix:
        print(f" -> {n_files_fixed} files were fixed")
    if len(files_with_wrong_license) > 0 and not fix:
        print("---------------------------")
        print(
            f""" -> {len(files_with_wrong_license)} files have the wrong license or are missing a license altogether!
    Please check the output above."""
        )

    return {
        "total": n_files,
        "with_license": n_files_with,
        "generated": n_files_generated,
        "geth": n_files_geth,
        "license_removed": n_files_lic_removed,
        "lgpl3": n_files_lgpl3,
        "encl": n_files_encl,
        "wrong_license": len(files_with_wrong_license) - n_files_fixed,
    }


def check_if_in_exempt_files(file: str) -> bool:
    """
    Check if the file is in the exempt files list.
    """

    for exempt_file in EXEMPT_FILES:
        if re.search(exempt_file, file):
            return True
    return False


def check_license_in_file(file: str, checked_license: List[str]) -> bool | str:
    """
    Check if the file has the license.
    """

    with open(file, "r") as f:
        lines = f.readlines()

        if "generated" in lines[0].lower() or "do not edit" in lines[0].lower():
            return "generated"
        elif "ethereum" in lines[0].lower():
            return "geth"

        for expected_line, line in zip(checked_license, lines[: len(checked_license)]):
            if line != expected_line:
                print(" - ", file)
                return False

        return True


def fix_license_in_file(file: str, checked_license: List[str]) -> None:
    """
    Fix the license in a file by adding or replacing the license header.
    """
    with open(file, "r") as f:
        lines = f.readlines()

    # Check if it's a generated file or geth file - skip these
    if len(lines) > 0 and ("generated" in lines[0].lower() or "do not edit" in lines[0].lower()):
        return
    if len(lines) > 0 and "ethereum" in lines[0].lower():
        return

    # Find where the existing license ends (look for empty line after license lines)
    # License headers are typically 2 lines, then an empty line
    license_end = 0
    for i in range(min(len(lines), len(checked_license) + 1)):
        if i < len(lines) and lines[i].strip() == "":
            license_end = i
            break
        if i == len(checked_license):
            license_end = i

    # Remove existing license if present (first 2-3 lines before empty line)
    if license_end > 0:
        lines = lines[license_end:]

    # Prepend the correct license
    lines = checked_license + ["\n"] + lines

    # Write back
    with open(file, "w") as f:
        f.writelines(lines)

    print(f"Fixed: {file}")


if __name__ == "__main__":
    fix = "--fix" in sys.argv
    
    # Find the path argument (skip --fix)
    args = [arg for arg in sys.argv[1:] if arg != "--fix"]
    
    if len(args) < 1:
        print("Usage: python check_licenses.py [--fix] <path>")
        print("  --fix: Automatically fix files with missing or incorrect licenses")
        print("Checking current directory by default...")
        path = "."
    else:
        path = args[0]
    
    if fix:
        print("FIX MODE: Will modify files with missing/incorrect licenses\n")
    
    result = check_licenses_in_path(path, FILTER, fix=fix)
    if result["wrong_license"] > 0:
        sys.exit(1)
